In [ ]:
import numpy as np

In [ ]:
a=[1,2,3,4,5]
b=np.array(a)
c=np.array([1,3,5])
print(a)
print(b)
print(c)

[1, 2, 3, 4, 5]
[1 2 3 4 5]
[1 3 5]


In [ ]:
b=a
c=a.copy()
b[0]=99
print(a)
print(b)
print(c)

[99, 2, 3, 4, 5]
[99, 2, 3, 4, 5]
[1, 2, 3, 4, 5]


In [ ]:
print(b[2])
print(a[2])
print(c[-1])
print(b[0:2])


3
3
5
[99, 2]


In [ ]:
a=[1,2,3,4,5]
b=np.array(a)
c=np.array([1,3,5])
print(a*2)
print(b*2)
print(c+3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]
[4 6 8]


In [ ]:
a=np.array([1,2,3],dtype=int)
b=np.array([1,1,2,2,3,3],dtype=float)
a1=np.array([1,2,3],dtype=float)
c=np.array([1,1,0],dtype=bool)
print(a)
print(b)
print(a1)
print(c)
print()

[1 2 3]
[1. 1. 2. 2. 3. 3.]
[1. 2. 3.]
[ True  True False]


b=np.array([[[1,2],[3,4],[100,101,12]]])
print(b)

In [ ]:
a=np.identity(10,dtype=int)
b=np.eye(7,7, k=+2,dtype=int)
c=np.eye(7,7, k=-2,dtype=int)
print(a)
print('\n\n')
print(b)
print('\n\n')
print(c)


[[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]]



[[0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]



[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0]]


In [ ]:
a = np.arange(0, 10, step=5)
b = np.arange(1, 10, step=5)
c = np.arange(0, 10, step=1)
d = np.arange(0, 10, step=3)

print(a)
print(b)
print(c)
print(d)

[0 5]
[1 6]
[0 1 2 3 4 5 6 7 8 9]
[0 3 6 9]


In [ ]:
a = np.linspace(0, 10, num=5, endpoint=True, retstep=True)
b = np.linspace(1, 10, num=5, endpoint=True, retstep=False)
c = np.linspace(0, 10, num=5, endpoint=False, retstep=False)

print(a)
print(b)
print(c)

(array([ 0. ,  2.5,  5. ,  7.5, 10. ]), 2.5)
[ 1.    3.25  5.5   7.75 10.  ]
[0. 2. 4. 6. 8.]


In [ ]:
a = np.array([1, 2, 3, 4, 5])

print(a)
print("\n")
print(a[3:])
print("\n")
print(a[1:-1]) 
print("\n")
print(a[0:3:2])


[1 2 3 4 5]


[4 5]


[2 3 4]


[1 3]


In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a[0:8:3])

[1 4 7]


In [ ]:
a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]])
a.shape = (6,2)
print(a)


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [ ]:
a = np.array([[[1, 2, 3], [4, 5, 6]],
              [[7, 8, 9], [10, 11, 12]],
              [[13, 14, 15], [16, 17, 18]]])
print(a)
a.shape = (2,3,3)
print(a)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [ ]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])
b = np.ones(3, dtype = int)

print(a + b)
print('+'*40)
print(a - b)
print('+'*40)
print(a * b)
print('+'*40)
print(a / b)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
++++++++++++++++++++++++++++++++++++++++
[[0 1 2]
 [3 4 5]
 [6 7 8]]
++++++++++++++++++++++++++++++++++++++++
[[1 2 3]
 [4 5 6]
 [7 8 9]]
++++++++++++++++++++++++++++++++++++++++
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [ ]:
a=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
b=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(a*b)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [ ]:
a = np.array(
    [[1, 2], 
     [3, 4]])
b = np.array(
    [[1, 3], 
     [2, 4]])

print(a*b)

ma = np.mat(a)
mb = np.mat(b)

print(ma*mb)

[[ 1  6]
 [ 6 16]]
[[ 5 11]
 [11 25]]
